### ISSUE TITLE
Feature request: BCLinExtrapolate

### ISSUE THREAD

**Issue by floswald** [timholy/Grid.jl#32]
hi!

I thought it would be very useful to have the boundary condition `BCLinExtrapolate` which would linearly extrapolate the function outside lower and upper bounds, using the first and last two gridpoints respectively to compute this extrapolation.

**Comment by gaabriel** [comment]
This would be amazing! I would love to be able to use linear extrapolation!

**Comment by timholy** [comment]
See Interpolate.jl, where most of this already works.

**Comment by gaabriel** [comment]
@timholy Interpolate.jl has no documentation and no equivalent to CoordInterpGrid. Is this package no longer being developed? Thanks!

**Comment by floswald** [comment]
I think Tim meant tlycken/Interpolations.jl?

**Comment by tlycken** [comment]
@gaabriel, @floswald Yes, I think `Interpolations.jl` is the interesting package here. It's still not on feature-parity with `Grid.jl`, but if something corresponding to `CoordInterpGrid` is the deal breaker for you, it should be relatively easy to port the one in `Grid.jl` to work with `Interpolations.jl` instead. In fact, I have been meaning to do that myself, but I just haven't gotten to it (and of course, a pull request would be very welcome!).

Regarding documentation, I know it is lacking, but that is partly because the API isn't 100% final yet. There are some examples in [this IJulia notebook](http://nbviewer.ipython.org/github/tlycken/Interpolations.jl/blob/master/doc/Interpolations.jl.ipynb), and there's plenty of documentation of the implementation details in the [`doc/latex`](http://github.com/tlycken/Interpolations.jl/blob/master/doc/latex) folder.

**Comment by gaabriel** [comment]
Thank you for replying, @tlycken ! Without CoordInterpGrid I would need to always translate between my grid and the integer indices, and I doubt I could do that efficiently. It's an interpolation in itself, albeit trivial conceptually. So it's matter of both convenience and potentially performance, I think.

When I said documentation I meant more like a self-contained example of e.g. multilinear interpolation and extrapolation. For example, in my application I have a function with 2 parameters and another with 3. And I think bilinear and trilinear interpolation and extrapolation is all I need. (This would be interp2 and interpn in matlab.)

Thank you for your time and effort on this!

**Comment by tlycken** [comment]
To answer your last question first: no, you can't `Pkg.add("Interpolations")` just yet. (The details are that I haven't tagged a version of `Interpolations.jl` yet, since I wanted to get a few more features in place first. However, it seems the library is already getting some traction, so I'm seriously considering changing my stance on this, so it might become possible in the near future.) In the meantime, use `Pkg.clone()` (which will do the same thing, but you'll have to be more specific with the url).

As for examples, did you look at the IJulia notebook I linked to? It seems to me that all the information should already be there - it has all the components you need, albeit perhaps not utilized in exactly the combination you looked for. Something like `Interpolation(data, Linear(OnGrid()), ExtrapLinear())`, given a multidimensional array `data`, should give you a multilinear interpolation with linear extrapolation in all directions.
